---
- name: Copy and run allusers.sh with CSV
  hosts: test
  gather_facts: false
  become: true

  vars:
    dest_dir: "/tmp/allusers_task"

  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: "0755"

    - name: Copy allusers.sh to remote
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/allusers.sh"
        dest: "{{ dest_dir }}/allusers.sh"
        mode: "0755"

    - name: Copy newusers.csv to remote
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/newusers.csv"
        dest: "{{ dest_dir }}/newusers.csv"
        mode: "0644"

    - name: Execute allusers.sh with newusers.csv
      ansible.builtin.command:
        cmd: "./allusers.sh ./newusers.csv"
        chdir: "{{ dest_dir }}"
      register: run_out
      changed_when: true
      # If you want the task to fail when the script returns non-zero:
      # failed_when: run_out.rc != 0

    - name: Show script stdout (if any)
      ansible.builtin.debug:
        msg: "{{ (run_out.stdout | default('')) | trim }}"
      when: (run_out.stdout | default('')) | trim != ''

    - name: Show script stderr (if any)
      ansible.builtin.debug:
        msg: "{{ (run_out.stderr | default('')) | trim }}"
      when: (run_out.stderr | default('')) | trim != ''
