---
- name: Run allusers.sh if present
  hosts: test
  gather_facts: false
  become: true

  vars:
    base_dir: /tmp/semaphore/project_1/repository_3_template_8
    script_path: "{{ base_dir }}/allusers.sh"
    csv_path: "{{ base_dir }}/newusers.csv"

  tasks:
    - name: Check if allusers.sh exists
      ansible.builtin.stat:
        path: "{{ script_path }}"
      register: script_stat

    - name: Check if newusers.csv exists
      ansible.builtin.stat:
        path: "{{ csv_path }}"
      register: csv_stat

    - name: Make allusers.sh executable
      ansible.builtin.file:
        path: "{{ script_path }}"
        mode: "0755"
      when:
        - script_stat.stat.exists
        - script_stat.stat.isreg

    - name: Execute allusers.sh with newusers.csv
      ansible.builtin.shell: |
        ./allusers.sh newusers.csv
      args:
        chdir: "{{ base_dir }}"
      when:
        - script_stat.stat.exists
        - script_stat.stat.isreg
        - csv_stat.stat.exists
        - csv_stat.stat.isreg
      register: run_out
      changed_when: true

    - name: Show script output (stdout)
      ansible.builtin.debug:
        var: run_out.stdout
      when: run_out is defined and run_out.stdout != ""

    - name: Show script errors (stderr)
      ansible.builtin.debug:
        var: run_out.stderr
      when: run_out is defined and run_out.stderr != ""
