---
- name: Run allusers.sh if present
  hosts: test
  gather_facts: false
  become: true

  vars:
    base_dir: .
    script_path: "{{ base_dir }}/allusers.sh"
    csv_path: "{{ base_dir }}/newusers.csv"

  tasks:
    - name: Check if allusers.sh exists
      ansible.builtin.stat:
        path: "{{ script_path }}"
      register: script_stat

    - name: Check if newusers.csv exists
      ansible.builtin.stat:
        path: "{{ csv_path }}"
      register: csv_stat

    - name: Proceed only if both files exist
      block:
        - name: Make allusers.sh executable
          ansible.builtin.file:
            path: "{{ script_path }}"
            mode: "0755"

        - name: Execute allusers.sh with newusers.csv
          ansible.builtin.command:
            cmd: "{{ script_path }} {{ csv_path }}"
          register: run_out
          changed_when: true

        - name: Show script stdout (if any)
          ansible.builtin.debug:
            msg: "{{ (run_out.stdout | default('')) | trim }}"
          when: (run_out.stdout | default('')) | trim != ''

        - name: Show script stderr (if any)
          ansible.builtin.debug:
            msg: "{{ (run_out.stderr | default('')) | trim }}"
          when: (run_out.stderr | default('')) | trim != ''
      when:
        - script_stat.stat.exists
        - script_stat.stat.isreg
        - csv_stat.stat.exists
        - csv_stat.stat.isreg

    - name: Skip message if files missing
      ansible.builtin.debug:
        msg: >
          Skipping: required files not found.
          allusers.sh exists={{ script_stat.stat.exists | default(false) }},
          newusers.csv exists={{ csv_stat.stat.exists | default(false) }}
      when: not (script_stat.stat.exists and csv_stat.stat.exists)
