---
- hosts: test
  become: true
  tasks:
    - name: Get current working directory
      ansible.builtin.shell: pwd
      register: current_working_directory

    - name: Display current working directory
      debug:
       msg: "The current working directory is: {{ current_working_directory.stdout }}"

    - name: Change script permission
      file:
        path: /add_users.sh
        owner: semaphore
        group: semaphore
        mode: a+x
        
    - name: Execute the script
      ansible.builtin.shell:
        cmd: ./add_users.sh users.csv
