---
- name: Add users to the LZSCC_323 group and refresh sessions
  hosts: lab_all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false  # Disabled to avoid fact-gathering issues

  vars:
    LZSCC_323_users:
      - "karbukov"  #Replace with actual usernames, e.g., ['user1', 'user2']
      - "iacovidi"

  tasks:
    - name: Debug configured users
      ansible.builtin.debug:
        msg: "Users to add to LZSCC_323 group: {{ LZSCC_323_users }}"

    - name: Ensure LZSCC_323 group exists
      ansible.builtin.group:
        name: LZSCC_323
        state: present

    - name: Add users to LZSCC_323 group
      ansible.builtin.user:
        name: "{{ item }}"
        groups: LZSCC_323
        append: yes
      loop: "{{ LZSCC_323_users }}"
      register: user_update
      failed_when: user_update.failed and 'user does not exist' not in user_update.msg

    - name: Debug user update result
      ansible.builtin.debug:
        msg: "{{ user_update.results | select('failed') | map(attribute='msg') | list }}"
      when: user_update.results is defined and user_update.results | select('failed') | list | length > 0

    - name: Verify users are in LZ_323 group
      ansible.builtin.command: "getent group LZSCC_323"
      register: group_check
      failed_when: "item not in group_check.stdout"
      changed_when: false
      loop: "{{ LZSCC_323_users }}"
      loop_control:
        label: "{{ item }}"
      when: user_update.results is defined and user_update.results | select('failed') | list | length == 0

    - name: Validate LZSCC_323 group membership
      ansible.builtin.command: groups {{ item }}
      register: group_check
      changed_when: false
      failed_when: false
      loop: "{{ LZSCC_323_users }}"
      when: user_update.results is defined and not user_update.results | select('failed') | list | length > 0

    - name: Display LZSCC_323 group membership
      ansible.builtin.debug:
        msg: >-
          {{
            'User ' + item.item + ' is in groups: ' + item.stdout + ' (LZSCC_323 group: ' +
            ('present' if 'LZSCC_323' in item.stdout else 'missing') + ')'
          }}
      loop: "{{ group_check.results | default([]) }}"
      when: group_check.results is defined
