---
- hosts: lu_1
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false  # Temporarily disable to avoid permission issues
  
  tasks:
    - name: Check sudo access
      command: whoami
      register: whoami_result
      
    - name: Display current user
      debug:
        var: whoami_result.stdout
