---
- hosts: test_client
  become: true  # Disable privilege escalation
  tasks:
    - name: Check current user
      ansible.builtin.command: whoami
      register: current_user
      
    - name: Display current user
      ansible.builtin.debug:
        var: current_user.stdout
        
    - name: Install apache2 (skip if no sudo)
      ansible.builtin.package:
        name: apache2
        state: absent
      ignore_errors: true
