---
- name: Change user password
  hosts: new_device
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false

  vars:
    target_user: "semaphore"
    new_password: "sema!0g12"

  tasks:
    - name: Change user password
      user:
        name: "{{ target_user }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always
