---
- name: Change user password
  hosts: lab1
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false

  vars:
    target_user: "semaphore"
    new_password: "$6$KqXZWXRIzeO2zcSv$LWTXoTpfAlzFxBUyXAkgsAkyY1hnkSBKgoj/1To9Okli.SDOct7fYJSsu2lqHGkK8JG7/oMkHBJ9hBQL5bJLp0"

  tasks:
    - name: Change user password
      user:
        name: "{{ target_user }}"
        password: "{{ new_password | password_hash('sha512') }}"
        update_password: always

    - name: Verify password change
      shell: "echo 'Password changed successfully for {{ target_user }}'"
      changed_when: false
