---
- name: Check if Docker is installed
  hosts: lab3
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: true

  tasks:
    - name: Check for Docker installation
      ansible.builtin.command: command -v docker
      register: docker_check
      changed_when: false
      failed_when: false

    - name: Display Docker installation status
      ansible.builtin.debug:
        msg: "{{ 'Docker is installed at ' + docker_check.stdout if docker_check.rc == 0 else 'Docker is not installed on this host' }}"
