---
- name: Configure NTP servers for systemd-timesyncd
  hosts: lab_all
  become: yes
    become_method: sudo
  become_user: root

  tasks:
    - name: Ensure desired NTP servers are set in timesyncd.conf
      ansible.builtin.lineinfile:
        path: /etc/systemd/timesyncd.conf
        regexp: '^#?NTP='
        line: 'NTP=0.de.pool.ntp.org 1.de.pool.ntp.org 2.de.pool.ntp.org 3.de.pool.ntp.org'
        insertafter: '^\[Time\]'
        state: present
        backup: yes

    - name: Reload systemd manager configuration
      ansible.builtin.shell: systemctl daemon-reload

    - name: Restart systemd-timesyncd service
      ansible.builtin.service:
        name: systemd-timesyncd
        state: restarted
