---
- name: Test connection and gather basic info
  hosts: lab_clients
  gather_facts: true
  
  tasks:
  - name: Ping web servers
      ping:
      register: ping_result
      
    - name: Display connection information
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          IP: {{ ansible_default_ipv4.address }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          User: {{ ansible_user_id }}
