---
- name: Test connection and gather basic info
  hosts: lab_clients
  tasks:
    - name: Ping hosts to test connectivity
      ansible.builtin.ping:
      register: ping_result
      failed_when: ping_result.failed

  tasks:
    - name: Check sudo access
      command: whoami
      register: whoami_result
      
    - name: Display current user
      debug:
        var: whoami_result.stdout   

    - name: Display ping result
      ansible.builtin.debug:
        msg: "Ping result for {{ inventory_hostname }}: {{ ping_result.ping }}"

    - name: Display connection information
      ansible.builtin.debug:
        msg: |
          Host: {{ inventory_hostname }}
          IP: {{ ansible_default_ipv4.address | default('No IPv4 address') }}
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          User: {{ ansible_user_id }}
