---
- name: Sync latest passwords for all users across all machines
  hosts: lu_1  # Define 'all_machines' group in your inventory with all relevant hosts
  become: yes

  tasks:
    - name: Get local shadow file entries
      command: "cat /etc/shadow"
      register: local_shadow
      changed_when: false
      no_log: true

    - name: Parse local users and last change dates
      set_fact:
        local_users: "{{ local_shadow.stdout_lines | select('match', '^[^:]+:[^:]+:[0-9]+:') | map('regex_replace', '^([^:]+):[^:]+:([0-9]+):.*$', '\\1:\\2') | list }}"
      no_log: true

    - name: Gather shadow entries from all hosts
      command: "cat /etc/shadow"
      register: all_shadows
      delegate_to: "{{ item }}"
      loop: "{{ groups['all_machines'] }}"
      changed_when: false
      no_log: true

    - name: Parse all users and last change dates from all hosts
      set_fact:
        all_users: "{{ all_shadows.results | map(attribute='item') | zip(all_shadows.results | map(attribute='stdout_lines') | map('select', 'match', '^[^:]+:[^:]+:[0-9]+:') | map('map', 'regex_replace', '^([^:]+):[^:]+:([0-9]+):.*$', '\\1:\\2') | dict }}"
      no_log: true

    - name: Determine latest password changes for each user
      set_fact:
        latest_changes: "{{ latest_changes | default({}) | combine({item.key: {'host': item.value[0], 'lastchange': item.value[1] | int} }) }}"
      loop: "{{ all_users | dict2items | map('combine', {'value': {'0': item.value[0], '1': (all_users | dict2items | selectattr('key', 'equalto', item.key) | map(attribute='value') | map('map', 'split', ':') | map('last') | map('int') | max)}}) | list }}"
      no_log: true

    - name: Fetch shadow entries for users with newer passwords
      command: "grep ^{{ item.key }}: /etc/shadow"
      register: source_shadow
      delegate_to: "{{ item.value.host }}"
      loop: "{{ latest_changes | dict2items }}"
      when: "{{ local_users | select('match', '^' + item.key + ':') | map('split', ':') | map('last') | map('int') | first | default(0) < item.value.lastchange }}"
      no_log: true

    - name: Update shadow entries for users with newer passwords
      lineinfile:
        path: /etc/shadow
        regexp: "^{{ item.item.key }}:"
        line: "{{ item.stdout }}"
        owner: root
        group: shadow  # Adjust group if necessary (common is 'shadow' or 'root')
        mode: '0640'
        backup: yes
      loop: "{{ source_shadow.results | select('skipped', 'undefined') }}"
      when: "{{ item.skipped is not defined }}"
      no_log: true
