---
- name: Sync latest passwords for all users across all machines
  hosts: lu_1
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Check if at least two hosts exist in inventory
      fail:
        msg: "At least two hosts are required in the inventory to sync passwords"
      when: groups['lu_1'] | length < 2
      run_once: true

    - name: Debug available hosts
      debug:
        msg: "Available hosts: {{ groups['lu_1'] | list }}"
      when: debug_mode | default(false)
      run_once: true

    - name: Verify shadow file exists and is accessible
      ansible.builtin.stat:
        path: /etc/shadow
      register: shadow_stat
      failed_when: not shadow_stat.stat.exists or not shadow_stat.stat.readable

    - name: Debug shadow file status
      debug:
        msg: "Shadow file exists: {{ shadow_stat.stat.exists }}, readable: {{ shadow_stat.stat.readable }}"
      when: debug_mode | default(false)

    - name: Get local shadow file entries
      command: "cat /etc/shadow"
      register: local_shadow
      changed_when: false
      failed_when: local_shadow.rc != 0
      no_log: false  # Temporarily disabled for debugging

    - name: Debug local shadow output
      debug:
        msg: "Local shadow output: {{ local_shadow.stdout_lines | default([]) }}"
      when: debug_mode | default(false)

    - name: Parse local users and last change dates
      set_fact:
        local_users: "{{ local_shadow.stdout_lines | select('match', '^[^:]+:[^:]*:[0-9]*:') | map('regex_replace', '^([^:]+):[^:]*:([0-9]*):.*$', '\\1:\\2') | list | default([]) }}"
      no_log: true
      failed_when: local_users is not defined or local_users | length == 0

    - name: Debug local_users
      debug:
        msg: "{{ local_users }}"
      when: debug_mode | default(false)

    - name: Gather shadow entries from all hosts
      command: "cat /etc/shadow"
      register: all_shadows
      delegate_to: "{{ item }}"
      loop: "{{ groups['all'] }}"
      changed_when: false
      failed_when: false  # Allow failures to be filtered later
      no_log: false  # Temporarily disabled for debugging

    - name: Debug all_shadows output
      debug:
        msg: "Shadow output for {{ item.item }}: rc={{ item.rc | default('undefined') }}, skipped={{ item.skipped | default(false) }}, stdout_lines={{ item.stdout_lines | default([]) }}, stderr={{ item.stderr | default('') }}"
      loop: "{{ all_shadows.results }}"
      when: debug_mode | default(false)

    - name: Filter valid shadow results
      set_fact:
        valid_shadows: "{{ all_shadows.results | select('defined') | reject('skipped') | select('attr', 'rc') | select('match', 'rc', 0) | list | default([]) }}"
      no_log: false  # Temporarily disabled for debugging
      failed_when: valid_shadows is not defined or (groups['all'] | length > 0 and valid_shadows | length == 0)
      run_once: true

    - name: Debug valid_shadows
      debug:
        msg: "Valid shadows: {{ valid_shadows | map(attribute='item') | list }}"
      when: debug_mode | default(false)
      run_once: true

    - name: Parse all users and last change dates from all hosts
      set_fact:
        all_users: "{{ valid_shadows | map(attribute='item') | zip(valid_shadows | map(attribute='stdout_lines') | map('select', 'match', '^[^:]+:[^:]*:[0-9]*:') | map('map', 'regex_replace', '^([^:]+):[^:]*:([0-9]*):.*$', '\\1:\\2') | dict | default({}) }}"
      no_log: true
      failed_when: all_users is not defined or (valid_shadows | length > 0 and all_users | length == 0)
      run_once: true

    - name: Debug all_users
      debug:
        msg: "{{ all_users }}"
      when: debug_mode | default(false)

    - name: Determine latest password changes for each user
      set_fact:
        latest_changes: "{{ latest_changes | default({}) | combine({item.key: {'host': item.value[0], 'lastchange': item.value[1] | int} }) }}"
      loop: "{{ all_users | dict2items | map('combine', {'value': {'0': item.value[0], '1': (all_users | dict2items | selectattr('key', 'equalto', item.key) | map(attribute='value') | map('map', 'split', ':') | map('last') | map('int') | max)}}) | list }}"
      no_log: true
      when: all_users | length > 0
      run_once: true

    - name: Fetch shadow entries for users with newer passwords
      command: "grep ^{{ item.key }}: /etc/shadow"
      register: source_shadow
      delegate_to: "{{ item.value.host }}"
      loop: "{{ latest_changes | dict2items }}"
      when: "{{ local_users | select('match', '^' + item.key + ':') | map('split', ':') | map('last') | map('int') | first | default(0) < item.value.lastchange and item.value.host != inventory_hostname }}"
      no_log: true

    - name: Update shadow entries for users with newer passwords
      lineinfile:
        path: /etc/shadow
        regexp: "^{{ item.item.key }}:"
        line: "{{ item.stdout }}"
        owner: root
        group: shadow
        mode: '0640'
        backup: yes
      loop: "{{ source_shadow.results | select('skipped', 'undefined') }}"
      when: "{{ item.skipped is not defined }}"
      no_log: true
