---
- name: Ensure users are in specified groups from CSV
  hosts: lab_all
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: no

  vars:
    csv_file: "./users.csv"

  tasks:
    - name: Read user data from CSV
      set_fact:
        userlist: "{{ lookup('community.general.csvfile', csv_file, delimiter=',') }}"

    - name: Ensure user is present
      ansible.builtin.user:
        name: "{{ item['Username'] }}"
        state: present
      loop: "{{ userlist }}"
      loop_control:
        label: "{{ item['Username'] }}"

    - name: Ensure group exists
      ansible.builtin.group:
        name: "{{ item['Groups'] }}"
        state: present
      loop: "{{ userlist }}"
      loop_control:
        label: "{{ item['Groups'] }}"

    - name: Get user's current groups
      shell: id -nG "{{ item['Username'] }}"
      register: current_groups
      changed_when: false
      loop: "{{ userlist }}"
      loop_control:
        label: "{{ item['Username'] }}"

    - name: Add user to group if not present
      ansible.builtin.user:
        name: "{{ item['Username'] }}"
        groups: "{{ item['Groups'] }}"
        append: yes
      when: item['Groups'] not in current_groups.results[loop.index0].stdout.split()
      loop: "{{ userlist }}"
      loop_control:
        label: "{{ item['Username'] }}"

    - name: Display already exists if user in group
      debug:
        msg: "User {{ item['Username'] }} already exists in group {{ item['Groups'] }}"
      when: item['Groups'] in current_groups.results[loop.index0].stdout.split()
      loop: "{{ userlist }}"
      loop_control:
        label: "{{ item['Username'] }}"
